### ISSUE TITLE
Minimum length?

### ISSUE THREAD

**Issue by OKNoah** [zabracks/markovchain-generator#1]
Thanks for the module. I use it to generate dummy-text for running tests of web forms. However, some of the forms have validation that requires the input to have a certain length (say, 16 chars). Would be cool if there was an option to ensure each generated string has at least 16 characters or whatever.

**Comment by hailbopp** [comment]
I'd say that that point it sort of ceases to be a strict Markov Chain implementation, since there may not be a given state transition path from the first state to a string with length greater than the minimum.

What you could do is just continue to append output from the module until a target string's length is >= the minimum, I suppose.
